# Test Stand Configuration File
#
# Please adapt the configuration here to reflect the realities of your setup.

# Serial connection to the test target (device under test)
target = "/dev/tty.usbmodem1302B0252"

# Serial connection to the test assistant
assistant = "/dev/tty.usbmodem130280422"
