# Test Stand Configuration File
#
# Please adapt the configuration here to reflect the realities of your setup.

# Serial connection to the test target (device under test)
target = "/dev/ttyACM0"

# Serial connection to the Serial-to-USB converter connected to the target
serial = "/dev/ttyACM0"
