name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Cortex-M0+ target
      run: |
        rustup target install thumbv6m-none-eabi
    - name: Install Cortex-M4 target
      run: |
        rustup target install thumbv7em-none-eabi
    - name: Build
      run: |
        ./scripts/build.sh
