name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Cortex-M0+ target
      run: |
        rustup target install thumbv6m-none-eabi
    - name: Build
      run: |
        ./scripts/build.sh
